import DashboardLayout from "@/components/DashboardLayout";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { defaultSiteContent, type SiteContent } from "@shared/siteContent";
import { ArrowUpRight, Check, Globe2, Loader2, LockKeyhole, Plus, Save, ShieldCheck, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type FieldProps = {
  label: string;
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  multiline?: boolean;
  hint?: string;
};

function Field({ label, value, onChange, placeholder, multiline = false, hint }: FieldProps) {
  const fieldClass = "mt-2 w-full rounded-xl border border-white/10 bg-[#15131b] px-3 py-2.5 text-sm text-white outline-none transition focus:border-[#b98cff] focus:ring-2 focus:ring-[#b98cff]/20";
  return <label className="block"><span className="font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[#b9b1c5]">{label}</span>{multiline ? <textarea value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} rows={3} className={`${fieldClass} resize-y`} /> : <input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className={fieldClass} />}{hint && <span className="mt-1.5 block text-xs leading-5 text-[#91899f]">{hint}</span>}</label>;
}

function Panel({ title, description, children }: { title: string; description: string; children: React.ReactNode }) {
  return <section className="rounded-[1.6rem] border border-white/10 bg-[#121015] p-5 shadow-[0_18px_50px_rgba(0,0,0,.18)] sm:p-7"><div className="mb-6 border-b border-white/10 pb-5"><h2 className="font-display text-xl font-black uppercase tracking-[-.07em] text-white">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#aaa2b6]">{description}</p></div>{children}</section>;
}

function cloneDefaults() { return structuredClone(defaultSiteContent); }

export default function AdminPanel() {
  const { user, loading } = useAuth();
  const isAdmin = user?.role === "admin";
  const { data, isLoading } = trpc.siteContent.admin.get.useQuery(undefined, { enabled: isAdmin, retry: false, refetchOnWindowFocus: false });
  const [draft, setDraft] = useState<SiteContent>(cloneDefaults);
  const utils = trpc.useUtils();
  const saveMutation = trpc.siteContent.admin.update.useMutation({
    onSuccess: async (saved) => {
      setDraft(saved);
      await Promise.all([utils.siteContent.admin.get.invalidate(), utils.siteContent.public.invalidate()]);
      toast.success("Изменения опубликованы на сайте");
    },
    onError: (error) => toast.error(error.message || "Не удалось сохранить изменения"),
  });

  useEffect(() => { if (data) setDraft(data); }, [data]);

  const title = useMemo(() => draft.branding.siteName || "Мой сайт", [draft.branding.siteName]);
  const setBranding = (key: keyof SiteContent["branding"], value: string) => setDraft((current) => ({ ...current, branding: { ...current.branding, [key]: value } }));
  const setHero = (key: keyof SiteContent["hero"], value: string) => setDraft((current) => ({ ...current, hero: { ...current.hero, [key]: value } }));
  const setAbout = (key: keyof SiteContent["about"], value: string) => setDraft((current) => ({ ...current, about: { ...current.about, [key]: value } }));
  const setServices = (key: keyof SiteContent["services"], value: string) => setDraft((current) => ({ ...current, services: { ...current.services, [key]: value } }));
  const setCompany = (key: keyof SiteContent["company"], value: string) => setDraft((current) => ({ ...current, company: { ...current.company, [key]: value } }));
  const setClosing = (key: keyof SiteContent["closing"], value: string) => setDraft((current) => ({ ...current, closing: { ...current.closing, [key]: value } }));

  if (loading) return <div className="grid min-h-screen place-items-center bg-[#0c0c0c] text-white"><Loader2 className="h-7 w-7 animate-spin text-[#b98cff]" /></div>;
  if (!user) return <div className="grid min-h-screen place-items-center bg-[#0c0c0c] px-5 text-white"><div className="max-w-md rounded-[2rem] border border-white/10 bg-[#15131b] p-8 text-center"><LockKeyhole className="mx-auto h-8 w-8 text-[#b98cff]" /><h1 className="mt-5 font-display text-2xl font-black uppercase tracking-[-.08em]">Закрытая панель</h1><p className="mt-3 text-sm leading-6 text-[#aaa2b6]">Этот раздел не виден на публичном сайте. Войдите через защищённую авторизацию владельца.</p><button onClick={() => startLogin()} className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#b98cff] px-5 py-3 font-mono text-xs font-bold uppercase tracking-[.12em] text-[#160e22]">Войти <ArrowUpRight className="h-4 w-4" /></button></div></div>;
  if (!isAdmin) return <div className="grid min-h-screen place-items-center bg-[#0c0c0c] px-5 text-white"><div className="max-w-md rounded-[2rem] border border-white/10 bg-[#15131b] p-8 text-center"><ShieldCheck className="mx-auto h-8 w-8 text-[#ff9ed7]" /><h1 className="mt-5 font-display text-2xl font-black uppercase tracking-[-.08em]">Нет доступа</h1><p className="mt-3 text-sm leading-6 text-[#aaa2b6]">Редактирование сайта доступно только назначенному владельцу.</p><a href="/" className="mt-7 inline-flex rounded-full border border-white/20 px-5 py-3 font-mono text-xs font-bold uppercase tracking-[.12em]">Вернуться на сайт</a></div></div>;

  const updateProject = (index: number, key: keyof SiteContent["projects"][number], value: string) => setDraft((current) => ({ ...current, projects: current.projects.map((project, projectIndex) => projectIndex === index ? { ...project, [key]: value } : project) }));
  const addProject = () => setDraft((current) => current.projects.length >= 6 ? current : ({ ...current, projects: [...current.projects, { number: String(current.projects.length + 1).padStart(2, "0"), name: "Новый проект", category: "Категория", description: "Коротко опишите задачу и результат проекта.", url: "", visual: "violet" }] }));
  const removeProject = (index: number) => setDraft((current) => current.projects.length <= 1 ? current : ({ ...current, projects: current.projects.filter((_, projectIndex) => projectIndex !== index) }));

  return <DashboardLayout><div className="mx-auto max-w-6xl pb-16"><div className="flex flex-col gap-6 border-b border-white/10 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[.16em] text-[#b98cff]">Скрытая панель владельца</p><h1 className="mt-3 font-display text-[clamp(2.2rem,5vw,4.5rem)] font-black uppercase leading-[.84] tracking-[-.1em] text-white">Редактор<br />сайта.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-[#aaa2b6]">Изменения сохраняются в базу и сразу подставляются в публичный сайт. Раздел не добавлен в навигацию и защищён ролью владельца.</p></div><div className="flex flex-wrap gap-3"><a href="/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-4 py-3 font-mono text-[10px] font-semibold uppercase tracking-[.12em] text-white">Открыть сайт <Globe2 className="h-4 w-4" /></a><button disabled={saveMutation.isPending || isLoading} onClick={() => saveMutation.mutate(draft)} className="inline-flex items-center gap-2 rounded-full bg-[#b98cff] px-5 py-3 font-mono text-[10px] font-bold uppercase tracking-[.12em] text-[#160e22] disabled:opacity-60">{saveMutation.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Сохранить</button></div></div>

    {isLoading ? <div className="grid min-h-64 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-[#b98cff]" /></div> : <div className="mt-8 grid gap-6">
      <Panel title="Бренд и навигация" description="Название сайта, пункты публичного меню и нижняя подпись."><div className="grid gap-4 md:grid-cols-2"><Field label="Название сайта" value={draft.branding.siteName} onChange={(value) => setBranding("siteName", value)} /><Field label="Нижняя подпись" value={draft.branding.footerNote} onChange={(value) => setBranding("footerNote", value)} /><Field label="Меню: обо мне" value={draft.branding.navAbout} onChange={(value) => setBranding("navAbout", value)} /><Field label="Меню: услуги" value={draft.branding.navServices} onChange={(value) => setBranding("navServices", value)} /><Field label="Меню: проекты" value={draft.branding.navProjects} onChange={(value) => setBranding("navProjects", value)} /><Field label="Меню: контакт" value={draft.branding.navContact} onChange={(value) => setBranding("navContact", value)} /></div></Panel>
      <Panel title="Первый экран" description="Крупный заголовок, правая подпись и главный призыв к действию."><div className="grid gap-4 md:grid-cols-3"><Field label="Строка 1" value={draft.hero.lineOne} onChange={(value) => setHero("lineOne", value)} /><Field label="Строка 2" value={draft.hero.lineTwo} onChange={(value) => setHero("lineTwo", value)} /><Field label="Строка 3" value={draft.hero.lineThree} onChange={(value) => setHero("lineThree", value)} /></div><div className="mt-4 grid gap-4 md:grid-cols-[1fr_.35fr]"><Field label="Подпись справа" value={draft.hero.note} onChange={(value) => setHero("note", value)} multiline /><Field label="Кнопка" value={draft.hero.ctaLabel} onChange={(value) => setHero("ctaLabel", value)} /></div></Panel>
      <Panel title="Обо мне" description="Светлая портретная сцена и её подписи."><div className="grid gap-4 md:grid-cols-2"><Field label="Верхняя подпись" value={draft.about.eyebrow} onChange={(value) => setAbout("eyebrow", value)} /><Field label="Тег" value={draft.about.tag} onChange={(value) => setAbout("tag", value)} /><Field label="Заголовок: строка 1" value={draft.about.lineOne} onChange={(value) => setAbout("lineOne", value)} /><Field label="Заголовок: строка 2" value={draft.about.lineTwo} onChange={(value) => setAbout("lineTwo", value)} /><Field label="Акцентное слово" value={draft.about.accentWord} onChange={(value) => setAbout("accentWord", value)} /><Field label="Заголовок: строка 3" value={draft.about.lineThree} onChange={(value) => setAbout("lineThree", value)} /><Field label="Описание" value={draft.about.description} onChange={(value) => setAbout("description", value)} multiline /><Field label="Кнопка" value={draft.about.ctaLabel} onChange={(value) => setAbout("ctaLabel", value)} /></div></Panel>
      <Panel title="Услуги" description="Тексты поверх анимированного видеофона, статистика и CTA."><div className="grid gap-4 md:grid-cols-2"><Field label="Верхняя подпись" value={draft.services.eyebrow} onChange={(value) => setServices("eyebrow", value)} /><Field label="Кнопка Telegram" value={draft.services.ctaLabel} onChange={(value) => setServices("ctaLabel", value)} /><Field label="Этап 01" value={draft.services.statOneLabel} onChange={(value) => setServices("statOneLabel", value)} /><Field label="Этап 02" value={draft.services.statTwoLabel} onChange={(value) => setServices("statTwoLabel", value)} /><Field label="Этап 03" value={draft.services.statThreeLabel} onChange={(value) => setServices("statThreeLabel", value)} /><Field label="Пояснение 01" value={draft.services.annotationOne} onChange={(value) => setServices("annotationOne", value)} multiline /><Field label="Пояснение 02" value={draft.services.annotationTwo} onChange={(value) => setServices("annotationTwo", value)} multiline /><Field label="Заголовок 1" value={draft.services.headlineOne} onChange={(value) => setServices("headlineOne", value)} /><Field label="Заголовок 2" value={draft.services.headlineTwo} onChange={(value) => setServices("headlineTwo", value)} /><Field label="Заголовок 3" value={draft.services.headlineThree} onChange={(value) => setServices("headlineThree", value)} /></div></Panel>
      <Panel title="Контакты и компания" description="Данные для футера и кнопки «Начать проект». Поле Telegram должно быть полной ссылкой."><div className="grid gap-4 md:grid-cols-2"><Field label="Название компании" value={draft.company.companyName} onChange={(value) => setCompany("companyName", value)} /><Field label="Телефон" value={draft.company.phone} onChange={(value) => setCompany("phone", value)} placeholder="+7 …" /><Field label="E-mail" value={draft.company.email} onChange={(value) => setCompany("email", value)} placeholder="hello@example.com" /><Field label="Telegram" value={draft.company.telegramUrl} onChange={(value) => setCompany("telegramUrl", value)} placeholder="https://t.me/username" /><Field label="Адрес" value={draft.company.address} onChange={(value) => setCompany("address", value)} /><Field label="Юридическая строка" value={draft.company.legalLine} onChange={(value) => setCompany("legalLine", value)} /></div></Panel>
      <Panel title="Проекты" description="Добавляйте реальные кейсы, ссылки и описания. Пустая ссылка отображается как «Ссылка появится»."><div className="grid gap-5">{draft.projects.map((project, index) => <div key={`${project.number}-${index}`} className="rounded-2xl border border-white/10 bg-[#17141d] p-4"><div className="mb-4 flex items-center justify-between"><p className="font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[#b98cff]">Кейс {index + 1}</p><button onClick={() => removeProject(index)} disabled={draft.projects.length <= 1} className="inline-flex items-center gap-2 text-xs text-[#ffabc7] disabled:opacity-30"><Trash2 className="h-4 w-4" />Удалить</button></div><div className="grid gap-4 md:grid-cols-2"><Field label="Номер" value={project.number} onChange={(value) => updateProject(index, "number", value)} /><Field label="Название" value={project.name} onChange={(value) => updateProject(index, "name", value)} /><Field label="Категория" value={project.category} onChange={(value) => updateProject(index, "category", value)} /><Field label="Ссылка" value={project.url} onChange={(value) => updateProject(index, "url", value)} placeholder="https://…" /><Field label="Описание" value={project.description} onChange={(value) => updateProject(index, "description", value)} multiline /><label className="block"><span className="font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[#b9b1c5]">Цвет карточки</span><select value={project.visual} onChange={(event) => updateProject(index, "visual", event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#15131b] px-3 py-2.5 text-sm text-white outline-none"><option value="violet">Фиолетовый</option><option value="lime">Лаймовый</option><option value="coral">Коралловый</option></select></label></div></div>)}<button onClick={addProject} disabled={draft.projects.length >= 6} className="inline-flex w-fit items-center gap-2 rounded-full border border-dashed border-white/30 px-4 py-3 font-mono text-[10px] font-semibold uppercase tracking-[.12em] text-white disabled:opacity-30"><Plus className="h-4 w-4" />Добавить проект</button></div></Panel>
      <Panel title="Финальный призыв" description="Последний блок перед брифом."><div className="grid gap-4 md:grid-cols-2"><Field label="Подпись" value={draft.closing.eyebrow} onChange={(value) => setClosing("eyebrow", value)} /><Field label="Кнопка" value={draft.closing.ctaLabel} onChange={(value) => setClosing("ctaLabel", value)} /><Field label="Заголовок: строка 1" value={draft.closing.lineOne} onChange={(value) => setClosing("lineOne", value)} /><Field label="Заголовок: строка 2" value={draft.closing.lineTwo} onChange={(value) => setClosing("lineTwo", value)} /></div></Panel>
      <Panel title="Клиентский бриф" description="Главный заголовок, пояснение и заметка о конфиденциальности в форме заявки."><div className="grid gap-4 md:grid-cols-2"><Field label="Метка блока" value={draft.brief.label} onChange={(value) => setDraft((current) => ({ ...current, brief: { ...current.brief, label: value } }))} /><Field label="Заголовок" value={draft.brief.title} onChange={(value) => setDraft((current) => ({ ...current, brief: { ...current.brief, title: value } }))} multiline /><Field label="Вводный текст" value={draft.brief.intro} onChange={(value) => setDraft((current) => ({ ...current, brief: { ...current.brief, intro: value } }))} multiline /><Field label="Заметка о конфиденциальности" value={draft.brief.privacyNote} onChange={(value) => setDraft((current) => ({ ...current, brief: { ...current.brief, privacyNote: value } }))} multiline /></div></Panel>
    </div>}</div></DashboardLayout>;
}
