import BriefApplication from "@/components/BriefApplication";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ArrowDownRight, ArrowUpRight, Compass, ExternalLink, Mail, Menu, MessageCircle, PanelsTopLeft, Phone, Rocket, Send, ShieldCheck, X } from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";
import { useEffect, useRef, useState } from "react";
import { trpc } from "@/lib/trpc";
import { SiteInquiryDialog } from "@/components/SiteInquiryDialog";
import { defaultSiteContent, type SiteContent } from "@shared/siteContent";
import { resolvePublicMediaUrls } from "@shared/siteMedia";

function FadeIn({ children, delay = 0, className = "" }: { children: React.ReactNode; delay?: number; className?: string }) {
  const reduced = useReducedMotion();
  return <motion.div initial={reduced ? false : { opacity: 0, y: 28 }} whileInView={reduced ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.16 }} transition={{ duration: 0.72, delay, ease: [0.25, 0.1, 0.25, 1] }} className={className}>{children}</motion.div>;
}

function MagneticAvatar({ src }: { src?: string }) {
  const reduced = useReducedMotion();
  const imageRef = useRef<HTMLImageElement>(null);

  const move = (event: React.PointerEvent<HTMLDivElement>) => {
    if (reduced || !imageRef.current) return;
    const box = event.currentTarget.getBoundingClientRect();
    const x = ((event.clientX - box.left) / box.width - 0.5) * 46;
    const y = ((event.clientY - box.top) / box.height - 0.5) * 46;
    imageRef.current.style.transform = `translate3d(${x}px, ${y}px, 0) rotate(${x * 0.19}deg) scale(1.035)`;
  };

  const reset = () => { if (imageRef.current) imageRef.current.style.transform = "translate3d(0, 0, 0) rotate(0deg) scale(1)"; };

  return <div onPointerMove={move} onPointerLeave={reset} className="avatar-stage absolute bottom-0 left-1/2 z-10 h-[69%] w-[min(72vw,570px)] -translate-x-1/2 sm:h-[75%] sm:w-[min(60vw,640px)]" aria-label="Интерактивный 3D-объект"><span className="avatar-halo" aria-hidden="true" /><motion.div animate={reduced ? undefined : { y: [0, -12, 0], rotate: [0, 0.8, 0], scale: [1, 1.018, 1] }} transition={{ duration: 3.6, repeat: Infinity, ease: "easeInOut" }} className="avatar-float h-full w-full">{src ? <img ref={imageRef} src={src} alt="Стилизованный 3D-портрет создателя сайта" className="avatar-image h-full w-full object-contain object-bottom" /> : null}</motion.div></div>;
}

function AnimatedText({ text }: { text: string }) {
  return <p className="about-reveal mx-auto max-w-2xl text-center text-[clamp(1.08rem,2vw,1.45rem)] font-medium leading-relaxed text-[#d7e2ea]">{Array.from(text).map((character, index) => <motion.span key={`${character}-${index}`} initial={{ opacity: 0.22 }} whileInView={{ opacity: 1 }} viewport={{ once: true, amount: 0.4 }} transition={{ duration: 0.35, delay: Math.min(index * 0.012, 0.6) }}>{character}</motion.span>)}</p>;
}

function ProjectStackCard({ index, total, work }: { index: number; total: number; work: SiteContent["projects"][number] }) {
  const targetScale = 1 - (total - 1 - index) * 0.035;
  const isSkifiaCase = index === 0 && Boolean(work.url);
  const coverUrl = null;
  const caseScreenshots: Array<{ src: string; alt: string; label: string; kind: "hero" | "services" }> = [];

  return <div className="project-sticky h-[78vh] sm:h-[84vh]" style={{ top: `${96 + index * 28}px` }}><motion.article initial={{ opacity: 0, y: 34 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.24 }} transition={{ duration: 0.65, ease: [0.25, 0.1, 0.25, 1] }} className="project-sheet h-full" style={{ scale: targetScale }}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-4 sm:gap-7"><span className="font-display text-[clamp(3rem,8vw,7rem)] font-semibold leading-none tracking-[-.07em] text-[#d7e2ea]">{work.number}</span><div><p className="font-mono text-[10px] uppercase tracking-[0.17em] text-[#9faab4]">{work.category}</p><h3 className="mt-2 font-display text-2xl font-semibold tracking-[-.04em] text-white sm:text-4xl">{work.name}</h3></div></div>{work.url ? <a href={work.url} target="_blank" rel="noreferrer" className="live-button">Открыть сайт <ExternalLink className="h-4 w-4" /></a> : <span className="live-button live-button--muted">Ссылка появится <ArrowUpRight className="h-4 w-4" /></span>}</div><div className={`project-art project-art--${work.visual} mt-5 grid h-[calc(100%-130px)] grid-cols-[.7fr_1fr] gap-3 sm:mt-8`}><div className="grid grid-rows-2 gap-3">{caseScreenshots.length ? caseScreenshots.map((screenshot) => <figure key={screenshot.src} className="project-art__tile project-art__tile--screenshot"><img src={screenshot.src} alt={screenshot.alt} className={`project-case-screenshot project-case-screenshot--${screenshot.kind}`} loading="lazy" /><figcaption>{screenshot.label}</figcaption></figure>) : <><div className="project-art__tile project-art__tile--a"><span>{work.number}</span><b>visual<br />direction</b></div><div className="project-art__tile project-art__tile--b"><i /><i /><i /></div></>}</div><div className={`project-art__tile project-art__tile--hero ${coverUrl ? "project-art__tile--hero-cover" : ""}`}>{coverUrl && <><img src={coverUrl} alt="Визуальная обложка кейса Skifia" className="project-case-cover" /><span className="project-case-cover-wash" aria-hidden="true" /></>}<em>future<br />on<br />screen</em>{isSkifiaCase && <p className="project-case-summary"><span>результат / 01</span>{work.description}</p>}<span className="project-art__orb" /><small>case / {String(index + 1).padStart(2, "0")}</small></div></div></motion.article></div>;
}

function StorefrontSiteCard({ work, index, onRequest }: { work: SiteContent["projects"][number]; index: number; onRequest: (work: SiteContent["projects"][number]) => void }) {
  const [flipped, setFlipped] = useState(false);
  const coverUrl = work.coverUrl;
  const isSold = work.availability === "sold";
  const availabilityLabel = isSold ? "Продан" : "В продаже";
  const hasUrl = Boolean(work.url) && !isSold;
  const hostLabel = work.url ? work.url.replace(/^https?:\/\/(www\.)?/, "").split("/")[0] : "ваш-сайт.ru";
  const toggle = () => setFlipped((current) => !current);
  const onKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      toggle();
    }
  };

  return <motion.article initial={{ opacity: 0, y: 26 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.18 }} transition={{ duration: 0.55, delay: index * 0.08, ease: [0.22, 1, 0.36, 1] }} className="site-store-card"><div className={`site-store-card__flip ${flipped ? "is-flipped" : ""}`} role="button" tabIndex={0} aria-pressed={flipped} aria-label={`Показать подробности сайта ${work.name}`} onClick={toggle} onKeyDown={onKeyDown}><div className="site-store-card__face site-store-card__front"><div className="site-store-card__topline"><span>сайт / {work.number}</span><span className={`site-store-card__status site-store-card__status--${work.availability}`}>{availabilityLabel}</span></div><div className="site-store-card__browser"><div className="site-store-card__browser-bar"><i /><i /><i /><span>{hostLabel}</span></div><div className="site-store-card__preview">{coverUrl ? <img src={coverUrl} alt={`Превью сайта ${work.name}`} loading="lazy" /> : <div className={`site-store-card__placeholder site-store-card__placeholder--${work.visual}`}><span>ready<br />to<br />launch</span><i /></div>}<div className="site-store-card__preview-wash" /></div></div><div className="site-store-card__front-copy"><p>{work.category}</p><h3>{work.name}</h3><div className="site-store-card__sale-meta"><strong>{work.price}</strong><span>наведите или коснитесь</span></div></div></div><div className="site-store-card__face site-store-card__back"><span className={`site-store-card__badge site-store-card__badge--${work.availability}`}>{availabilityLabel}</span><div><p className="site-store-card__back-kicker">{work.category}</p><h3>{work.name}</h3><p className="site-store-card__description">{work.description}</p></div><div className="site-store-card__back-footer"><strong>{work.price}</strong>{isSold ? <span className="site-store-card__link site-store-card__link--sold">Уже продан</span> : <div className="site-store-card__actions">{hasUrl && <a href={work.url} target="_blank" rel="noreferrer" onClick={(event) => event.stopPropagation()} className="site-store-card__link">Открыть <ArrowUpRight className="h-4 w-4" /></a>}<button type="button" onClick={(event) => { event.stopPropagation(); onRequest(work); }} className="site-store-card__inquiry">Оставить заявку</button></div>}</div></div></div></motion.article>;
}

const serviceEase: [number, number, number, number] = [0.22, 1, 0.36, 1];

function ServiceShowcase({ content, videoUrl }: { content: SiteContent; videoUrl?: string }) {
  const reduced = useReducedMotion();
  const fadeUp = (delay: number) => ({ initial: reduced ? false : { opacity: 0, y: 32 }, whileInView: reduced ? undefined : { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.2 }, transition: { delay, duration: 0.6, ease: serviceEase } });
  const serviceStats = [["01", content.services.statOneLabel], ["02", content.services.statTwoLabel], ["03", content.services.statThreeLabel]];
  const serviceWords = [content.services.headlineOne, content.services.headlineTwo, content.services.headlineThree];
  const serviceNotes = [content.services.annotationOne, content.services.annotationTwo, content.services.annotationThree];
  const serviceIllustrations = [Compass, PanelsTopLeft, Rocket];

  return <section id="services" className="services-showcase relative z-10 isolate min-h-screen overflow-hidden rounded-t-[42px] bg-[#cbb5f0] px-5 py-6 text-[#201529] sm:rounded-t-[60px] sm:px-8 sm:py-8 md:px-12">
    {videoUrl ? <video className="services-video pointer-events-none absolute inset-0 -z-20 h-full w-full object-cover" autoPlay loop muted playsInline preload="metadata" aria-hidden="true"><source src={videoUrl} /></video> : null}
    <div className="services-wash pointer-events-none absolute inset-0 -z-10" />
    <div className="mx-auto flex min-h-[calc(100svh-3rem)] max-w-[1600px] flex-col sm:min-h-[calc(100svh-4rem)]">
      <div className="grid grid-cols-[1fr_auto] items-center gap-4"><motion.div {...fadeUp(0)} className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-[#5e0ed7]"><i className="h-2.5 w-2.5 rounded-full bg-[#5e0ed7]" /></span><span className="font-mono text-[9px] font-semibold uppercase tracking-[.17em]">{content.services.eyebrow}</span></motion.div><motion.a {...fadeUp(0.2)} href={content.company.telegramUrl || "#brief"} target={content.company.telegramUrl ? "_blank" : undefined} rel={content.company.telegramUrl ? "noreferrer" : undefined} className="services-primary-cta">{content.services.ctaLabel} <ArrowUpRight className="h-4 w-4" /></motion.a></div>
      <div className="relative z-10 flex flex-1 items-center justify-end py-10 sm:py-12"><div className="services-stage-grid relative z-10">{serviceStats.map(([number, label], index) => { const ServiceIcon = serviceIllustrations[index]; return <div key={number} className="services-stage"><motion.div {...fadeUp(0.24 + index * 0.12)} className="services-stage-stat"><p className="font-display text-[clamp(2.2rem,5vw,4.4rem)] font-semibold leading-none tracking-[-.1em]"><span className="mr-1 align-top text-[.4em] text-[#5e0ed7]">+</span>{number}</p><p className="mt-2 whitespace-pre-line font-mono text-[8px] font-semibold leading-tight tracking-[.12em] sm:text-[10px]">{label}</p></motion.div><motion.article initial={reduced ? false : { opacity: 0, y: 24, scale: 0.97 }} whileInView={reduced ? undefined : { opacity: 1, y: 0, scale: 1 }} whileHover={reduced ? undefined : { y: -6, scale: 1.015 }} viewport={{ once: true, amount: 0.22 }} transition={{ delay: 0.56 + index * 0.1, duration: 0.52, ease: serviceEase }} className="services-annotation-card"><ServiceIcon aria-hidden="true" className="service-stage-icon" /><span>{String(index + 1).padStart(2, "0")}</span><p>{serviceNotes[index]}</p><i aria-hidden="true" /></motion.article></div>; })}</div></div>
      <div className="flex justify-end pb-4 sm:pb-7"><h2 className="text-right font-display text-[clamp(2.7rem,8.7vw,8.8rem)] font-semibold leading-[.77] tracking-[-.07em]">{serviceWords.map((word, index) => <span key={`${word}-${index}`} className="services-word block overflow-hidden"><motion.span initial={reduced ? false : { y: "112%" }} whileInView={reduced ? undefined : { y: 0 }} viewport={{ once: true, amount: 0.25 }} transition={{ delay: 0.38 + index * 0.14, duration: 0.7, ease: serviceEase }} className="block">{word}</motion.span></span>)}</h2></div>
    </div>
  </section>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [inquiryWork, setInquiryWork] = useState<SiteContent["projects"][number] | null>(null);
  const [privacyOpen, setPrivacyOpen] = useState(false);
  const reduced = useReducedMotion();
  const { data: storedContent } = trpc.siteContent.public.useQuery(undefined, { staleTime: 60_000, refetchOnWindowFocus: false });
  const { data: mediaAssets } = trpc.media.public.useQuery(undefined, { staleTime: 60_000, refetchOnWindowFocus: false });
  const content = storedContent ?? defaultSiteContent;
  const { avatar: avatarUrl, servicesVideo: servicesVideoUrl, aboutVideo: aboutVideoUrl } = resolvePublicMediaUrls(mediaAssets);

  useEffect(() => { document.title = content.branding.siteName; }, [content.branding.siteName]);

  useEffect(() => {
    const sectionId = window.location.hash.replace("#", "") || new URLSearchParams(window.location.search).get("section") || "";
    if (!sectionId) return;
    const timeout = window.setTimeout(() => document.getElementById(sectionId)?.scrollIntoView({ behavior: "auto", block: "start" }), 0);
    return () => window.clearTimeout(timeout);
  }, []);

  return <div className="creator-shell min-h-screen overflow-x-clip bg-[#0c0c0c] text-[#d7e2ea]">
    <header className="creator-nav absolute inset-x-0 top-0 z-30"><div className="mx-auto flex max-w-[1600px] items-center justify-between px-6 pt-6 sm:px-10 sm:pt-8"><a href="#top" className="font-display text-sm font-black uppercase tracking-[-0.06em] text-[#d7e2ea]">{content.branding.siteName}</a><nav className="hidden items-center gap-8 font-medium uppercase tracking-wider text-[#d7e2ea] sm:flex sm:text-sm lg:gap-12 lg:text-lg"><a href="#about" className="transition-opacity hover:opacity-70">{content.branding.navAbout}</a><a href="#services" className="transition-opacity hover:opacity-70">{content.branding.navServices}</a><a href="#projects" className="transition-opacity hover:opacity-70">{content.branding.navProjects}</a><a href="#brief" className="transition-opacity hover:opacity-70">{content.branding.navContact}</a></nav><button type="button" onClick={() => setMenuOpen((value) => !value)} aria-label={menuOpen ? "Закрыть меню" : "Открыть меню"} aria-expanded={menuOpen} className="grid h-10 w-10 place-items-center rounded-full border border-[#d7e2ea]/50 text-[#d7e2ea] sm:hidden">{menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>{menuOpen && <nav className="mx-6 mt-4 flex flex-col gap-4 rounded-2xl border border-white/15 bg-[#161616]/95 p-5 font-mono text-xs uppercase tracking-[.14em] sm:hidden"><a href="#about" onClick={() => setMenuOpen(false)}>{content.branding.navAbout}</a><a href="#services" onClick={() => setMenuOpen(false)}>{content.branding.navServices}</a><a href="#projects" onClick={() => setMenuOpen(false)}>{content.branding.navProjects}</a><a href="#brief" onClick={() => setMenuOpen(false)} className="text-[#f2b1ff]">{content.branding.navContact}</a></nav>}</header>

    <main>
      <section id="top" className="relative flex min-h-screen flex-col overflow-hidden"><div className="hero-noise pointer-events-none absolute inset-0" /><div className="hero-glow pointer-events-none absolute left-1/2 top-[38%] h-[42vw] w-[42vw] min-h-64 min-w-64 -translate-x-1/2 -translate-y-1/2 rounded-full" /><MagneticAvatar src={avatarUrl} /><div className="pointer-events-none relative z-20 mx-auto flex w-full max-w-[1600px] flex-1 flex-col px-6 pt-32 sm:px-10 sm:pt-40"><FadeIn className="pointer-events-auto overflow-hidden" delay={0.12}><h1 className="hero-heading whitespace-nowrap font-display text-[5.75vw] font-semibold leading-[.78] tracking-[-.07em] sm:text-[6.25vw] md:text-[6.5vw] lg:text-[7vw]">{content.hero.lineOne}<br />{content.hero.lineTwo.includes("создаю") ? <span>{content.hero.lineTwo}</span> : content.hero.lineTwo}<br />{content.hero.lineThree}</h1></FadeIn><div className="mt-auto flex justify-end pb-7 sm:pb-10"><div className="hero-sidecar pointer-events-auto relative z-20 flex max-w-[270px] flex-col items-end gap-5 text-right sm:max-w-[320px]"><FadeIn delay={0.3} className="hero-note">{content.hero.note}</FadeIn><FadeIn delay={0.45}><a href="#brief" className="contact-button">{content.hero.ctaLabel} <ArrowDownRight className="h-4 w-4" /></a></FadeIn></div></div></div></section>

      <section id="site-storefront" className="site-storefront relative overflow-hidden px-5 pb-16 pt-20 sm:px-8 sm:pb-24 sm:pt-28"><div className="site-storefront__glow pointer-events-none absolute -left-24 top-20 h-72 w-72 rounded-full" /><div className="site-storefront__glow site-storefront__glow--right pointer-events-none absolute -right-24 bottom-0 h-80 w-80 rounded-full" /><div className="relative mx-auto max-w-6xl"><FadeIn><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#bda4e7]">готовые решения / в наличии</p><div className="mt-4 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><h2 className="site-storefront__title">Сайты<br /><span>в наличии.</span></h2><p className="max-w-sm text-sm leading-6 text-[#b6afc0]">Выберите понравившуюся основу, откройте сайт и оставьте заявку. Карточка переворачивается, чтобы показать детали и перейти к просмотру.</p></div></FadeIn><div className="site-storefront__grid mt-10 sm:mt-14">{content.projects.map((work, index) => <StorefrontSiteCard key={`store-${work.number}-${index}`} work={work} index={index} onRequest={setInquiryWork} />)}</div></div></section>

      <section id="about" className="about-portrait relative isolate min-h-[110svh] overflow-hidden bg-[#edeef5] px-5 py-7 text-[#17171a] sm:min-h-[118svh] sm:px-8 sm:py-10 md:px-12"><motion.video initial={reduced ? false : { clipPath: "inset(0 100% 0 0)", x: "-10%" }} whileInView={reduced ? undefined : { clipPath: "inset(0 0% 0 0)", x: "0%" }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: 1.1, ease: [0.22, 1, 0.36, 1] }} autoPlay loop muted playsInline preload="metadata" className="about-portrait-video pointer-events-none absolute inset-x-0 top-[16vh] z-0 h-[92svh] w-full object-contain">{aboutVideoUrl ? <source src={aboutVideoUrl} /> : null}</motion.video><div className="about-portrait-mask pointer-events-none absolute inset-0 z-[1]" /><div className="relative z-10 mx-auto flex min-h-[calc(110svh-3.5rem)] max-w-[1600px] flex-col sm:min-h-[calc(118svh-5rem)]"><motion.div initial={reduced ? false : { opacity: 0, y: -18 }} whileInView={reduced ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6, ease: serviceEase }} className="flex items-center justify-between gap-4"><p className="font-mono text-[9px] font-semibold uppercase tracking-[.16em]">{content.about.eyebrow}</p><span className="rounded-full border border-black/15 bg-white/60 px-3 py-1.5 font-mono text-[8px] font-semibold uppercase tracking-[.14em] backdrop-blur-sm">{content.about.tag}</span></motion.div><div className="mt-14 max-w-3xl sm:mt-20 md:ml-[8%]"><motion.h2 initial={reduced ? false : { opacity: 0, y: 22 }} whileInView={reduced ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.3 }} transition={{ delay: 0.18, duration: 0.75, ease: serviceEase }} className="font-display text-[clamp(3rem,8.5vw,8.5rem)] font-semibold leading-[.79] tracking-[-.07em]">{content.about.lineOne}<br />{content.about.lineTwo} <span className="text-[#5e0ed7]">{content.about.accentWord}</span><br />{content.about.lineThree}</motion.h2></div><motion.div initial={reduced ? false : { opacity: 0, y: 26 }} whileInView={reduced ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ delay: 0.38, duration: 0.7, ease: serviceEase }} className="about-copy-card mt-auto grid gap-5 p-5 sm:max-w-xl sm:p-7 md:ml-auto"><p className="text-sm font-medium leading-relaxed text-black/72 sm:text-base">{content.about.description}</p><a href="#brief" className="about-portrait-cta">{content.about.ctaLabel} <ArrowUpRight className="h-4 w-4" /></a></motion.div></div></section>

      <ServiceShowcase content={content} videoUrl={servicesVideoUrl} />

      <section id="projects" className="projects-section relative z-20 -mt-10 rounded-t-[42px] bg-[#0c0c0c] px-5 pb-16 pt-24 sm:-mt-14 sm:rounded-t-[60px] sm:px-8 sm:pt-32"><div className="mx-auto max-w-6xl"><FadeIn><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#9da9b2]">Ваша коллекция опубликованных работ</p><h2 className="hero-heading mt-5 font-display text-[clamp(3.5rem,11vw,9.6rem)] font-semibold leading-[.77] tracking-[-.07em]">{content.branding.navProjects}</h2></FadeIn><div className="mt-12">{content.projects.map((work, index) => <ProjectStackCard key={`${work.number}-${index}`} index={index} total={content.projects.length} work={work} />)}</div></div></section>

      <section className="closing-section relative overflow-hidden bg-[#0c0c0c] px-5 pb-24 pt-8 sm:px-8"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-8 border-t border-[#d7e2ea]/20 pt-9 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#9da9b2]">{content.closing.eyebrow}</p><h2 className="mt-4 max-w-3xl font-display text-[clamp(2.8rem,7vw,6.4rem)] font-semibold leading-[.8] tracking-[-.06em] text-[#d7e2ea]">{content.closing.lineOne}<br />{content.closing.lineTwo}</h2></div><a href={content.company.telegramUrl || "#brief"} target={content.company.telegramUrl ? "_blank" : undefined} rel={content.company.telegramUrl ? "noreferrer" : undefined} className="contact-button shrink-0">{content.closing.ctaLabel} <ArrowDownRight className="h-4 w-4" /></a></div></section>

      <BriefApplication />
      {inquiryWork && <SiteInquiryDialog work={inquiryWork} open={Boolean(inquiryWork)} onOpenChange={(open) => { if (!open) setInquiryWork(null); }} />}
    </main>

    <footer className="border-t border-[#d7e2ea]/10 bg-[#0c0c0c] px-6 py-9 sm:px-10"><div className="mx-auto grid max-w-[1600px] gap-8 lg:grid-cols-[1.2fr_.8fr_auto] lg:items-end"><div><p className="font-display text-sm font-black uppercase tracking-[-.06em] text-[#d7e2ea]">{content.branding.siteName}</p><p className="mt-2 max-w-md text-xs leading-5 text-[#8c969e]">{content.branding.footerNote}</p><div className="mt-4 space-y-1.5 text-xs leading-5 text-[#c9c1d1]"><p>{content.company.companyName}</p>{content.company.taxId && <p>{content.company.taxId}</p>}{content.company.legalLine && <p className="text-[#8c8494]">{content.company.legalLine}</p>}</div></div><div><p className="font-mono text-[9px] font-semibold uppercase tracking-[.14em] text-[#ad9db9]">Контакты</p><div className="mt-3 flex flex-wrap gap-2"><a href={`tel:${content.company.phone.replace(/[^+\d]/g, "")}`} className="footer-contact-link"><Phone className="h-3.5 w-3.5" />{content.company.phone}</a><a href={`mailto:${content.company.email}`} className="footer-contact-link"><Mail className="h-3.5 w-3.5" />E-mail</a>{content.company.whatsappUrl && <a href={content.company.whatsappUrl} target="_blank" rel="noreferrer" className="footer-contact-link"><MessageCircle className="h-3.5 w-3.5" />WhatsApp</a>}{content.company.telegramUrl && <a href={content.company.telegramUrl} target="_blank" rel="noreferrer" className="footer-contact-link"><Send className="h-3.5 w-3.5" />Telegram</a>}</div><button type="button" onClick={() => setPrivacyOpen(true)} className="mt-4 inline-flex items-center gap-2 text-xs text-[#d5b8fa] transition hover:text-white"><ShieldCheck className="h-3.5 w-3.5" />Политика конфиденциальности</button></div><p className="font-mono text-[9px] uppercase tracking-[.14em] text-[#8c969e]">© {new Date().getFullYear()} / {content.branding.siteName}</p></div></footer>
    <Dialog open={privacyOpen} onOpenChange={setPrivacyOpen}><DialogContent className="max-h-[calc(100svh-2rem)] max-w-2xl overflow-y-auto border-white/10 bg-[#121015] p-5 text-white sm:p-7"><DialogHeader><DialogTitle className="font-display text-3xl font-semibold tracking-[-.06em]">Политика конфиденциальности</DialogTitle><DialogDescription className="text-[#aaa2b6]">Контактные данные и порядок обработки обращений.</DialogDescription></DialogHeader><div className="mt-4 space-y-5 text-sm leading-7 text-[#ddd5e4]"><p>{content.company.privacyPolicy}</p><div className="rounded-2xl border border-white/10 bg-[#19161e] p-4"><p className="font-mono text-[9px] font-semibold uppercase tracking-[.14em] text-[#a79eaf]">Администратор данных</p><p className="mt-2 text-white">{content.company.companyName}</p>{content.company.taxId && <p className="text-[#c8bfce]">{content.company.taxId}</p>}<a href={`mailto:${content.company.email}`} className="mt-3 inline-flex text-[#d8bbff] hover:text-white">{content.company.email}</a></div></div></DialogContent></Dialog>
  </div>;
}
